# -*- coding: utf-8 -*-
"""caltech_birds2010_IRNV3_pooling_outputs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B0FJ9GBHDB-rXwf6TKKD-_Ls8N00JNA2



## Identifying bird species using InceptionResNetV2-based model
---


This repository uses data provided by CalTech (citaiton as follows)

@techreport{WelinderEtal2010,
	Author = {P. Welinder and S. Branson and T. Mita and C. Wah and F. Schroff and S. Belongie and P. Perona},
	Institution = {California Institute of Technology},
	Number = {CNS-TR-2010-001},
	Title = {{Caltech-UCSD Birds 200}},
	Year = {2010}
}


The *inception* architechture introduce in 2013 (?) by researchers at Google is excellent for classifying images where the subject is likely to appear in various sizes/positions in the image data.
"""








"""### $\S$ 1: Model architechture

Below is a graphic showing the model design which will serve as the base for our classifier:

[image](https://1.bp.blogspot.com/-O7AznVGY9js/V8cV_wKKsMI/AAAAAAAABKQ/maO7n2w3dT4Pkcmk7wgGqiSX5FUW2sfZgCLcB/s1600/image00.png)
"""


"""#### Adding trainable layers to this model in order to fine-tune it's performance for our specific use case"""



